### ISSUE TITLE
When I run the "video_demo.py" file, an error message appears

### ISSUE THREAD

**Issue by shlsp** [goutamyg/SMAT#10]
When I run the "video_demo.py" file, an error message appears: KeyError: 'target_response,  can you help me check it?

**Comment by goutamyg** [comment]
Hi, I have commented the parts in the [script](https://github.com/goutamyg/SMAT/blob/main/lib/test/evaluation/tracker.py) that were causing the error.  Can you re-try running the demo script with these changes?

**Comment by shlsp** [comment]
> Hi, I have commented the parts in the [script](https://github.com/goutamyg/SMAT/blob/main/lib/test/evaluation/tracker.py) that were causing the error. Can you re-try running the demo script with these changes?

Thank you very much. The issue has been resolved.
